version: '3.8'
services:
  ginweb:
      image: ginweb
      container_name: ginweb
      build:
        context: .
        dockerfile: ./Dockerfile
      env_file:
        - .env
      ports:
        - "8080:8080"  # ホストのポートとコンテナのポートをマッピング
      volumes:
        - .:/app    # ローカルのソースコードをコンテナにマウント
      tty: true
  db:
    image: postgres:12.3-alpine
    ports:
      - "5555:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sa
      POSTGRES_DB: postgres
volumes:
  db_data: