// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Department is the predicate function for department builders.
type Department func(*sql.Selector)

// Employee is the predicate function for employee builders.
type Employee func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
